version: '3.0'

services:
  # initialize Airflow database
  initdb:
    image: clara690/job_airflow:${DOCKER_IMAGE_VERSION}
    command: uv run --env-file=.env airflow db init # initialize Airflow metadata DB
    restart: on-failure # restart if fails
    deploy:
      mode: replicated #swarm replicated mode
      replicas: 1 
      placement:
        constraints: [node.labels.airflow==true]  # 僅部署在標記為 airflow 的節點
    networks:
      - my_swarm_network

  # create airflow user
  create-user:
    image: clara690/job_airflow:${DOCKER_IMAGE_VERSION}
    # create user account 
    command: >-
      uv run --env-file=.env airflow users create
      --username admin --firstname clara --lastname tsai
      --role Admin -p admin
      --email clara80416@gmail.com
    depends_on:
      - initdb
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.airflow==true]
    networks:
      - my_swarm_network

  webserver:
    image: clara690/job_airflow:${DOCKER_IMAGE_VERSION}
    hostname: "airflow-webserver"  
    command: uv run --env-file=.env airflow webserver -p 5000  # 啟動 webserver，使用 5000 port
    depends_on:
      - initdb  
    restart: always  
    ports:
      - 5000:5000  
    environment:
      - TZ=Asia/Taipei 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.airflow==true]
    networks:
      - my_swarm_network
  scheduler:
    image: clara690/job_airflow:${DOCKER_IMAGE_VERSION}
    hostname: "airflow-scheduler"
    command: uv run --env-file=.env airflow scheduler  # start scheduler
    depends_on:
      - initdb
    restart: always
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.airflow==true]
    networks:
      - my_swarm_network

networks:
  my_swarm_network:
    external: true

